### ISSUE TITLE
Missing license and Chinese README.md

### ISSUE THREAD

**Issue by dlesnoff** [ringabout/data-structure-in-Nim#1]
I am interested by the sorting algorithms and the data structures this library contains, but:
1. There is no license
2. The descriptive README is in Chinese
3. The english README does not describe what this directory contains. While titles are explicit, it contains both DS, sorting algorithms
4. Tests contain benchmarks. Do you have any results concerning their performance ?

There is no library that does an extensive collection of data structures in Nim apart from this one.
I would be very happy to improve this library. I understand that these algorithms come from a Chinese blog post, but does it prevent you from adding a license?

**Comment by ringabout** [comment]
> I understand that these algorithms come from a Chinese blog post, but does it prevent you from adding a license?

I don't think so. I wasn't aware to add one. The code is in bad shape anyway.

**Comment by dlesnoff** [comment]
Thanks. I'll try to do 3. and 4. in a week or so.
Benchmarks and reorganization of the code is the subject of another issue (to be opened). I close this one.
